### ISSUE TITLE
Adipose sample is missing data file

### ISSUE THREAD

**Issue by goepp** [cellatlas/human#4]
Hi,
I noticed that sample [GSM3711788](https://github.com/cellatlas/human/tree/99732f1e07e365280f249aa2eacc19744a962ece/data/adipose/GSM3711788) is missing the `filter`, `metrics`, and `mx_out` folders.

**Comment by goepp** [comment]
Hi,
After closer examination, here is the list of samples which I have found to be missing data:

- no metadata.json: lung/GSM4213830
- no observation.json: blood/CRX102288 blood/CRX118014
- no filter folder:
lung/GSM4339774 lung/GSM3773109 lung/GSM4339771 lung/GSM3773122 lung/GSM4339770 adipose/GSM3711788
tonsil/GSM5051493 tonsil/GSM5051493 tonsil/GSM5051496 rectum/GSM3576396 kidney/GSM4145206 
kidney/GSM4145205 blood/GSM1676569 blood/GSM2560246 blood/GSM2560247 blood/GSM2560249
muscle/GSM4272893 muscle/GSM4272894 pancreas/all
- no mx_out folder: lung/GSM3773117 lung/GSM3773112
- no data at all: 
kidney/SRX3445570 kidney/SRX3445568 kidney/SRX3445567 kidney/SRX3445568 ileum/GSM3576431

In addition, there seems to be an error in the sample adipose/GSM3711758, as `matrix.mtx.gz`has 3790 rows while `barcodes.txt.gz`has only 2802 rows.

Hope this helps.

**Comment by sbooeshaghi** [comment]
Thank you! This is very helpful. We will investigate and report back.

**Comment by sbooeshaghi** [comment]
GSM4213830 done

I had to remove the CRX accessions since I was having trouble downloading the reads

GSM4339774 done
GSM3773109 removed
GSM4339771 done
GSM3773122 removed
GSM4339770 done
GSM3711788 done
GSM5051493 done
GSM5051493 done
GSM5051496 done
GSM3576396 done
GSM4145206 done
GSM4145205 removed
GSM1676569 removed
GSM2560246 removed
GSM2560247 removed
GSM2560249 removed 
GSM4272893 done
GSM4272894 removed
GSM3773117 removed
GSM3773112 removed

pancreas done
SRX3445570 done
SRX3445568 done
SRX3445567 done
SRX3445568 done
GSM3576431 done
GSM3711758

all anndata objects have been added in their respective folders (*/mx_out/adata.h5ad.gz).
