### ISSUE TITLE
Broken links in input dataset

### ISSUE THREAD

**Issue by TamaraPerteghella** [cellatlas/human#7]
Hi!

While downloading the data I came across a couple of issues; 
I took the liberty of reproducing the dataset.tsv file, fixing a bunch of broken links and some formatting issues. In this file you will not find any entry sequenced with celseq (as I understand is not supported), nor any experiment for which I did not find the respective folder in the atlas repo as of today.

Moreover, it came to my attention that some experiments do have the indexes (8bp sequences) in the *_1.fastqs.gz file which will not make causing the failure of the kb_count step. Below the list, hoping I don't forget any:

GSM373853*,
GSM373854*,
GSM373921*,
GSM3731527,
GSM373922*,
GSM476938*,

**Comment by sbooeshaghi** [comment]
Thank you for pointing this out! The FASTQ reads from those observations contain the barcode in *_2.fastq.gz and the cDNA in *_3.fastq.gz. The *_1.fastq.gz contains the index reads as you point out. 

https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR8984443&display=data-access

<img width="952" alt="image" src="https://github.com/cellatlas/human/assets/10369156/a3743aa0-7527-41fe-9686-b2b5148f01d1">

This is where the seqspec file would be useful in describing which fastq file has the barcode/umi. Relying on the R1/R2/I1 etc file name convention works most of the times but not always. The solution moving forward is to have seqspec read annotations for each observation so that FASTQ files can be mapped to their relevant contents; this is a work in progress. Note that for the matrices generated for the observations you listed we manually identified the reads containing the barcode/umi and passed them to kb-python appropriately. See e.g. https://github.com/cellatlas/human/blob/677b67dadf0c6d6213a9c674a26f597ada06c68d/data/GSM3738543/metrics/kb_info.json#L6

For now I'll close this issue and open a new one discussing the inclusion of seqspec read annotations so that the examples you identified can be preprocessed correctly.
